### ISSUE TITLE
nodetest task

### ISSUE THREAD

**Issue by catz** [mainmatter/ember-cookies#457]
Hello,

Just a friendly question. Is nodetest task still actual ? I'm trying to run it and getting errors. I suppose they were designed to test in "fastboot" mode?

```
yarn nodetest
yarn run v1.21.0
warning ../package.json: No license field
$ node node-tests/runner.js


  cookies access
    1) "before all" hook for "reads and writes cookies in FastBoot"
    2) "after all" hook for "reads and writes cookies in FastBoot"


  0 passing (4m)
  2 failing

  1) cookies access
       "before all" hook for "reads and writes cookies in FastBoot":
     Error: the object {
  "code": 1
  "errors": [
    "DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-data`\n    at PackageInfo.getAddonConstructor (/private/var/folders/dg/g9_8k11s3xx38bcj96w9qd580000gn/T/d-120712-71391-n3obni.8pnzb/pristine/node_modules/ember-cli/lib/models/package-info-cache/package-info.js:400:20)\n"
    "Using a version of ember-cli-shims prior to 0.1.0 will cause errors while loading Ember Data 2.3.0-beta.3+. Please update ember-cli-shims from undefined to 0.1.0.\n"
    "\n"
    "An error occurred in the constructor for ember-data at /private/var/folders/dg/g9_8k11s3xx38bcj96w9qd580000gn/T/d-120712-71391-n3obni.8pnzb/pristine/node_modules/ember-data\n"
    "\n"
  ]
  "output": [
    "DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: test-app -> ember-data -> ember-cli-babel\n"
    "DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: test-app -> ember-data -> ember-inflector -> ember-cli-babel\n"
  ]
  "signal": [null]
} was thrown, throw an Error :)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) cookies access
       "after all" hook for "reads and writes cookies in FastBoot":
     Error: You must call `startServer()` before calling `stopServer()`.
      at AddonTestApp.App.stopServer (node_modules/ember-cli-addon-tests/lib/models/app.js:52:11)
      at Context.<anonymous> (node-tests/acceptance/cookie-access-test.js:28:16)



error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by marcoow** [comment]
Ouch, we should fix that indeed
